### ISSUE TITLE
Helping tips like in PS4 version

### ISSUE THREAD

**Issue by Sergmachine** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#23]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Why not really? It can make the game similar with old console and PS4 editions. They can be turned off in options if player doesn't want to see them. Also they can describe a basics of controls.

**Additional context**
Submition by Sergey ESN

**Comment by IridescentRose** [comment]
This could be useful alongside the tutorial feature. I'll consider this more for singleplayer, but I'll see what can be done.

**Comment by IridescentRose** [comment]
Temporary wontfix, will be worked on in conjunction with #22
