### ISSUE TITLE
Sky clipping issues on PPSSPP

### ISSUE THREAD

**Issue by PhantomHorror** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#25]
**Describe the bug**
The sky can turn black in some positions.
**Screenshots**
![Screenshot_2019-11-17-15-37-27-071_org ppsspp ppssppgold](https://user-images.githubusercontent.com/53868992/69008439-27a0b300-0953-11ea-98d3-4e89134e5364.png)

**Additional context**
This bug isn't on PSP, only PPSSPP on Android.

**Comment by IridescentRose** [comment]
I'm not sure what can be done about this, but I'll see.

**Comment by IridescentRose** [comment]
Should have been fixed, but reopen if it doesn't fix in next pre release
