### ISSUE TITLE
A singleplayer crash (Options).

### ISSUE THREAD

**Issue by PhantomHorror** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#26]
**Describe the bug**
When you change any option from the settings menu, singleplayer will be crashing every time.

**To Reproduce**
1. Go to 'Options'
2. Click on 'any option'
3. Scroll down to 'Singleplayer'

**Expected behavior**
Expected not to cause crash after changing something from the options.

**Additional context**
It doesn't regard changing the languages, only options can cause crash.

**Comment by IridescentRose** [comment]
Weird issue, I'll check what is going wrong.
