### ISSUE TITLE
A singleplayer crash (Folder name).

### ISSUE THREAD

**Issue by PhantomHorror** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#27]
**Describe the bug**
Crashes every time you try to launch Singleplayer if the folder name is more than 5 symbols

**To Reproduce**
1. Change the name of the folder 'Game' to more than 5 symbols
2. Enter the game
3. Click on 'Singleplayer'
4. See crash, after some time PSP turns off

**Expected behavior**
Minecraft PSP Edition starts normally without crash and you can see a fully working sky without length limit of the folder name.

**Additional context**
Like the developer Iridescence commented, the reason can be in libpng.

**Comment by IridescentRose** [comment]
Possible to do with libpng, I may switch to stbi if the two are interchangeable

**Comment by IridescentRose** [comment]
Should be fixed when I work on #24 and #16

**Comment by IridescentRose** [comment]
Testing if this has been fixed.

**Comment by IridescentRose** [comment]
5 characters worked, which was the last established limit. Let's go further.

**Comment by IridescentRose** [comment]
Folder string "Minecraft-PSP" among others have worked!

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
Folder string "Minecraft-PSP" among others have worked!
