### ISSUE TITLE
Crash on Audio Event

### ISSUE THREAD

**Issue by PhantomHorror** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#29]
**Describe the bug**
On PSP in Singleplayer the game randomly crashes after a certain amount of time.

**To Reproduce**
1. Go to 'Minecraft PSP Edition'
2. Click on 'Singleplayer'
3. Wait nearly 30-40 seconds (differently every time)

**Expected behavior**
Minecraft PSP Edition normally work in Singleplayer and doesn't crash always after some time.

**Additional context**
Seems like there is no this bug on PPSSPP.

**Comment by IridescentRose** [comment]
Crash happens on sound load from audio event, need to trace further towards the point of failure.
