### ISSUE TITLE
Floating Worldtype from Indev

### ISSUE THREAD

**Issue by ghost** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#31]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In Minecraft Indev there are multiple world generation types, one of them being floating islands. These were pretty interesting to play on despite not being infinite, and I think they could fit the pocket experience well, even if they aren't in the current normal Minecraft version.

**Additional context**
Just thought it would be a nice feature.

**Comment by IridescentRose** [comment]
Interesting... do you have examples?

**Comment by ghost** [comment]
Yeah, here's a screenshot I found that shows the worldtype well.
![image](https://user-images.githubusercontent.com/44825201/70631946-f89cfa80-1bfb-11ea-8e80-712b079fcb02.png)

**Comment by IridescentRose** [comment]
Oh dang, this is pretty cool. I'd love to do this as a custom worldgen type!
