### ISSUE TITLE
v0.3 White screen then crash on android ppsspp

### ISSUE THREAD

**Issue by littlefunny233** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#37]
How can i get in the game successfully?
Everytime i open the game ,it only show the white screen and then crash
happend in the ppsspp psp emulator for android

**Comment by IridescentRose** [comment]
How did you go about installing it?

**Comment by littlefunny233** [comment]
> How did you go about installing it?

I downloaded the Minecraft-PSP.exe and EBOOT.PBP,
and moved the two files to :/PSP/GAME/ the directory on my android phone,
then i opened the game using ppsspp

**Comment by littlefunny233** [comment]
oops ,it may be my fault...
the .exe files didn't run on my amd ryzen pc but intel pc,
the game has been intalled successfully,i'll test it later
sorry!

**Comment by IridescentRose** [comment]
I'll close the issue. If it doesn't work, then reopen it
