### ISSUE TITLE
PSP immediately crashes when launching the game

### ISSUE THREAD

**Issue by Poomex** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#43]
**Describe the bug**
Launching the game immediately crashes the PSP and causes it to shut down after a few seconds. I'm using a PSP 2004 running 6.60 PRO-C firmware.

**To Reproduce**
1. Copy the new release to /PSP/GAME/MC/
2. Launch the game

**Expected behavior**
The game launches successfully

**Comment by IridescentRose** [comment]
Did you use the installer at all? I would expect it to crash if you didn't.

**Comment by Poomex** [comment]
I feel kind of stupid, but I can't seem to find any instructions on how to do that. Would you mind putting them into the readme?

**Comment by IridescentRose** [comment]
Check the README.MD (on the main page)
