### ISSUE TITLE
What's the usefulness of the launcher？

### ISSUE THREAD

**Issue by littlefunny233** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#44]
I use ppsspp the psp emulator for play this game,
ppsspp can not internet access,
so the launcher can not do any thing after I input my name and click the "play" button.
but if i directly find the main part of the game,
I can run the game and go in to a super flat world of the single player option, and can not quit(the "start" button is no usefulness),no inventory GUI,and more questions.
----------------------------------------------------------------------------------------
**So what's the usefulness of the launcher？Can you provide a offline version without launcher for the psp emulator users?**

**Comment by IridescentRose** [comment]
Just install with Launcher to the desktop, go to the Game folder inside and use the patch zip and apply it directly. It's supposed to rip Minecraft assets instead of distribution in the future.

**Comment by IridescentRose** [comment]
The game is in early development, there is no exiting yet nor advanced inventory features.

**Comment by IridescentRose** [comment]
Check README (main page) for more instructions
