### ISSUE TITLE
Very odd movement controls

### ISSUE THREAD

**Issue by transiient** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#52]
**Describe the bug**
The movement controls are really weird.

**To Reproduce**
1. Start a new game
2. Try to move around

**Expected behavior**
I'd expect the analog stick to move forward, back, left, and right. The X, O, triangle, and square buttons should look around. And then the D-pad can be used for switching items or other things. Just an idea.

Great port though so far.

**Comment by Tobiothan** [comment]
I feel it would be better if the shape buttons walk around and the analog stick looks around

**Comment by IridescentRose** [comment]
The original comment here makes no sense... that is the default. Customizable input is a planned feature in v0.5
