### ISSUE TITLE
hey verry nice mod

### ISSUE THREAD

**Issue by ghost** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#7]
I like how you make the vertex of flowers and grass moving it is so satisfiying and in real time ! I dont know how you made it xD

but the camera moving is a bad idea, verry bad lol

**Comment by IridescentRose** [comment]
Hello there! Yeah, The ambient movement is a bit out of hand. I'll probably change it with v0.3. I'm just about to prep the release for v0.2... I'm literally writing the update and checking out the performance numbers. v0.3 will be a big change 😃

**Comment by IridescentRose** [comment]
@Camxpspx123 If you want to figure out the vertex of flowers and grass moving, I think you will find the relevant changes in SimpleMeshChunk.cpp & CraftWorld2.cpp... It's a roughly implemented "vertex shader", which occurs at half the frame rate to keep it smooth without too much lag. Note, it also effects water, leaves, and plants like crops.
