### ISSUE TITLE
Make texture pack structure closer to Desktop Minecraft texture pack structure

### ISSUE THREAD

**Issue by Darthagnon** [NT-Bourgeois-Iridescence-Technologies/Minecraft2-PSP#8]
Hey, RedLikeRoses.
I followed woolio's mod back in the day. In his 2nd-to-last release, he included a bunch of sprite-sheet-based texture packs, which were awesome. Problem is, his final release dropped most of those texture packs, and changed the spritesheets slightly. I tried converting them over, but manually making spritesheets without any template in Paint.NET is a p.i.t.a. and I only ever converted one.

I was wondering, is there a hard requirement for spritesheets to be used in the texture packs? (e.g. like in Wagic, where a lot of stuff is "joined", even though it would make more sense as separate PNGs, JPGs, etc., due to RAM requirements)

I'd like to put forward a feature request, if possible, to make the file structure of texture packs as close as possible to Desktop Minecraft texture packs, e.g. instead of 1 custom spritesheet, many small jpgs. This would make it easier to port texture packs. Or is there a set of PSD templates for texture packs spritesheets?

**Comment by Darthagnon** [comment]
Am a little bit nervous, as I mentioned on /Talk, to start porting texture packs, if the structure is gonna change, too, so just thought I'd check. 

Potentially breaking it up into smaller, more logical (i.e. no whitespace) spritesheets would make aligning texture pack objects easier.

**Comment by IridescentRose** [comment]
@Darthagnon I remember that updating textures to 1.14 was a PITA too haha. As for the limits and constraints... The way actual Minecraft does this is by generating a huge spritesheet with the textures in the texture pack and making an image in memory. This requires some pretty intense GPU / CPU calculations and a lot of data transfer. This is fine in the initialization of Minecraft and is why it takes so long to open the game. 

As of v0.3, Minecraft2-PSP will be implementing a new client for multiplayer called Carnation. Carnation's core principal is to implement Minecraft (with some fun tweaks) and be compatible with genuine Minecraft clients. As a part of this, Carnation will seek to use the same data formats as Minecraft itself, including (unzipped) texturepacks. Carnation's implementation goal is to replicate Minecraft 1.12.2 (for now). So yes, using Minecraft Texturepacks is one of the goals of this game. Whether or not this is implemented in v0.3 or v0.4, is still unknown, as fundamentally rewriting a client is a task of unknown size.

I will add this to the tag of enhancements, and assign the task... hopefully we shall see soon which update it shall be ready for. I would also like to collaborate with you in the new design for better clarity and communication of ideas. If you have a means of contacting you, please send me your details as a private message on /Talk

**Comment by Darthagnon** [comment]
Wow! Thank you! I'd love to be involved! I'll ping you /Talk with my details (I'm Darth Agnon there, too)

**Comment by Darthagnon** [comment]
Pinged you on /Talk with contact details
